name: TingeePay
options:
  bundleIdPrefix: vn.tingee
targets:
  TingeePay:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    settings:
      MARKETING_VERSION: 1.6.2
      CURRENT_PROJECT_VERSION: 101
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    sources:
      - path: TingeePay/App
      - path: TingeePay/Resource
    info:
      path: TingeePay/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
    dependencies:
      - package: TingeePaySDK
packages:
  TingeePaySDK:
    path: .
